### ISSUE TITLE
result interpretation

### ISSUE THREAD

**Issue by francisduan** [pmlg/GAMEncoding#1]
Hi I saw your result is ~0.3, does this mean GAF leads to random guess?

**Comment by elfayoumi** [comment]
yes .33 is like randomSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Francis Duan <notifications@github.com> Date: 18/3/20  02:32  (GMT+08:00) To: pmlg/GAMEncoding <GAMEncoding@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [pmlg/GAMEncoding] result interpretation (#1) 
Hi I saw your result is ~0.3, does this mean GAF leads to random guess?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pmlg/GAMEncoding/issues/1",
"url": "https://github.com/pmlg/GAMEncoding/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by francisduan** [comment]
OMG, so do you think all the GAF results online are fakes?

**Comment by elfayoumi** [comment]
this is just an example Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Francis Duan <notifications@github.com> Date: 18/3/20  05:43  (GMT+08:00) To: pmlg/GAMEncoding <GAMEncoding@noreply.github.com> Cc: Ibrahim El-Fayoumi <elfayoumi@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [pmlg/GAMEncoding] result interpretation (#1) 
OMG, so do you think all the GAF results online are fakes?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pmlg/GAMEncoding/issues/1#issuecomment-600315458",
"url": "https://github.com/pmlg/GAMEncoding/issues/1#issuecomment-600315458",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by elfayoumi** [comment]
This was just an example, the point is it is very difficult to predict financial data, if we can we will be rich. 
Financial data are not stationary, and so predicting the future based on past values, is not possible with any good accuracy. Although accuracy in the example reached %39, it is close to %33 for a random guess.
